port: 4567
key: 'change_me'
blocked-uuids: []
log-every-deposit: true

# TLS (a.k.a. SSL) options
tls:
  # Set to true to enable TLS
  enabled: false
  # The path to your keystore (relative to ServerTap's plugin dir)
  keystore: keystore.jks
  # The password for the keystore
  keystorePassword: 'password'
  # Enforce Server Name Indication (SNI) or not
  sni: false

# Use this list to set allowed CORS Origins ("*" by default)
corsOrigins:
  - "*"