name: CountingMC
version: '${project.version}'
main: me.matiego.countingmc.Main
api-version: '1.20'
authors: [Matiego]
depend: [Vault]
commands:
  countingmc:
    permission: countingmc.countingmc
    usage: '§cUsage: /<command> [version|reload|enable|disable]'
  linkdiscord:
    permission: countingmc.linkdiscord
    usage: '§cUsage: /<command>'
permissions:
  countingmc.countingmc:
    default: op
  countingmc.linkdiscord:
    default: true

